services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: adauser
      POSTGRES_PASSWORD: adapass
      POSTGRES_DB: curso_spring
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - curso_spring_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - curso_spring_network

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    networks:
      - curso_spring_network

volumes:
  postgres_data:

networks:
  curso_spring_network:
    driver: bridge
